#!/usr/bin/env python3

from racemachine.trainer import Trainer
import racemachine.log as log

logger = log.get_logger(__name__)

def main():
  app = Trainer()
  app.train_detector()
  app.train_recognizer()

if __name__ == '__main__':
    main()
